public class ASCII2
{
	public static void main(String[]args)
	{
		System.out.println("...........................-//........................................//-...........................");
		System.out.println("........................-+hNMN+......................................+NMNh+-........................");
		System.out.println("......................:sNMMMMMMs....................................sMMMMMMNs:......................");
		System.out.println("..................../hMMMMMMMMMMy-................................-yMMMMMMMMMMh/....................");
		System.out.println("..................:hMMMMMMMMMMMMMh-..............................-dMMMMMMMMMMMMMh:..................");
		System.out.println("................-yMMMMMMMMMMMMMMMMm:............................:mMMMMMMMMMMMMMMMMy-................");
		System.out.println(".............../NMMMMMMMMMMMMMMMMMMN/........................../NMMMMMMMMMMMMMMMMMMN/...............");
		System.out.println("..............sMMMMMMMMMMMMMMMMMMMMMN+........................+NMMMMMMMMMMMMMMMMMMMMMs..............");
		System.out.println("............-hMMMMMMMMMMMMMMMMMMMMMMMMo......................oMMMMMMMMMMMMMMMMMMMMMMMMh-............");
		System.out.println("...........-hMMMMMMMMMMMMMMMMMMMMMMMMMMy....................yMMMMMMMMMMMMMMMMMMMMMMMMMMh-...........");
		System.out.println("...........yMMMMMMMMMMMMMMMMMMMMMMMMMMMMh-................-hMMMMMMMMMMMMMMMMMMMMMMMMMMMMy...........");
		System.out.println("..........+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd-..............-dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+..........");
		System.out.println(".........-NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm:............:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-.........");
		System.out.println(".........sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs:............:sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs.........");
		System.out.println("........-NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs-...-/oyhhyo/-...-sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-........");
		System.out.println("......../MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:...:yNMMMMMMMMNy:...:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/........");
		System.out.println("........sMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/...+NMMMMMMMMMMMMN+.../MMMMMMMMMMMMMMMMMMMMMMMMMMMMMs........");
		System.out.println("........yMMMMMMMMMMMMMMMMMMMMMMMMMMMMh...:NMMMMMMMMMMMMMMN:...hMMMMMMMMMMMMMMMMMMMMMMMMMMMMy........");
		System.out.println("........+ssssssssssssssssssssssssssss/...+MMMMMMMMMMMMMMMM+.../ssssssssssssssssssssssssssss+........");
		System.out.println(".........................................:NMMMMMMMMMMMMMMN:.........................................");
		System.out.println("..........................................+NMMMMMMMMMMMMN+..........................................");
		System.out.println("...........................................:yNMMMMMMMMNy:...........................................");
		System.out.println(".............................................-/syhhys/-.............................................");
		System.out.println("...........................................-............-...........................................");
		System.out.println("..........................................:mNhso++++oshNm:..........................................");
		System.out.println("........................................./NMMMMMMMMMMMMMMN/.........................................");
		System.out.println("........................................+NMMMMMMMMMMMMMMMMN+........................................");
		System.out.println(".......................................oMMMMMMMMMMMMMMMMMMMMo.......................................");
		System.out.println(".....................................-yMMMMMMMMMMMMMMMMMMMMMMy-.....................................");
		System.out.println("....................................-hMMMMMMMMMMMMMMMMMMMMMMMMh-....................................");
		System.out.println("...................................:mMMMMMMMMMMMMMMMMMMMMMMMMMMm:...................................");
		System.out.println("..................................:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:..................................");
		System.out.println(".................................+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+.................................");
		System.out.println("................................oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo................................");
		System.out.println("...............................yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy...............................");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
	}
}